### ISSUE TITLE
Not compatible with SWM 4.0.0

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticCite#107]
### Setup and configuration

- SMW version: 4.0.0
- SCI version: master
- MW version: 1.35
- DB (MySQL etc. and version): MariaDB

### Issue

After upgrading to SMW 4.0.0 the SemanticCite extension no longer works. Annotations with [[CiteRef::CitationKey]] no longer render as expected, i.e. as a citation marker<sup>[1]</sup>, instead a link to the CitationKey page is shown.

**Comment by krabina** [comment]
also the `{{#scite:}}` parser function does not work as if the extension was not installed. It shows in Special:Version, though.

![grafik](https://user-images.githubusercontent.com/4318745/188497989-7646fa3b-300a-4937-b3c7-3fee761a2afd.png)

**Comment by z929669** [comment]
I'm currently updating a SMW wiki and running into issues.

Installed Semantic Media Wiki 4.1, and Composer complained that Semantic Cite 2.1 depends on SMW ~3.0. To get around this, I'm using Semantic Cite dev-master. I'm guessing this extension is still working out kinks with SMW 4.x, but here's the error on update.php:
`PHP Fatal error:  Uncaught Error: Undefined constant "CACHE_ANYTHING" in /srv/sites/_wiki/extensions/SemanticCite/DefaultSettings.php:45
Stack trace:
#0 /srv/sites/_wiki/extensions/SemanticCite/SemanticCite.php(33): require_once()
#1 /srv/sites/_wiki/extensions/SemanticCite/SemanticCite.php(12): SemanticCite::load()
#2 /srv/sites/_wiki/vendor/composer/autoload_real.php(45): require('...')
#3 /srv/sites/_wiki/vendor/composer/autoload_real.php(49): {closure}()
#4 /srv/sites/_wiki/vendor/autoload.php(25): ComposerAutoloaderInit_mediawiki_vendor::getLoader()
#5 /srv/sites/_wiki/includes/AutoLoader.php(327): require_once('...')
#6 /srv/sites/_wiki/includes/Setup.php(114): require_once('...')
#7 /srv/sites/_wiki/maintenance/doMaintenance.php(83): require_once('...')
#8 /srv/sites/_wiki/maintenance/update.php(312): require_once('...')
#9 {main}
  thrown in /srv/sites/_wiki/extensions/SemanticCite/DefaultSettings.php on line 45`

The line in question is:
`$GLOBALS['scigMetadataResponseCacheType'] = CACHE_ANYTHING;`

**Comment by krabina** [comment]
See #110

**Comment by krabina** [comment]
Should be fixed with #116. If not, feel free to reopen.

**Comment by krabina** [comment]
Reopening. Just tried to add SemanticCite to a MW 1.39 installation and got the Uncaught Error: Undefined constant "CACHE_ANYTHING" error again. So it is not fixed.

**Comment by z929669** [comment]
> Reopening. Just tried to add SemanticCite to a MW 1.39 installation and got the Uncaught Error: Undefined constant "CACHE_ANYTHING" error again. So it is not fixed.

Thank you for noticing this. I was just about to post likewise on #116

**Comment by kghbln** [comment]
Ah, now I see all the rest. From #119 I get that this issue was fixed. @kizule Once you have done the CI please ping me and I will tag.

**Comment by krabina** [comment]
I don't see how #119 shoud fix the undefined constant error?

**Comment by krabina** [comment]
Just tried latest dev-master. Undefined constant error is still there. Must be fixed before we do a 3.x release.

**Comment by krabina** [comment]
What I find odd is how installing Semantic Cite completely breaks the wiki due to this error even if it is not enabled ein LocalSettings.php.
